/* Everything this extension ships but does not own, pulled in at build time.
 *
 *   ../frontend/py/learner.py        -> src/generated/assets.ts  (LEARNER_SOURCE)
 *   ../frontend/data/airfoil.csv     -> src/generated/assets.ts  (AIRFOIL_CSV)
 *                                    -> lite/files/airfoil.csv
 *   python/learner_runner.py         -> src/generated/assets.ts  (RUNNER_SOURCE)
 *   ../vscode-extension/webview/plots.css -> src/generated/assets.ts (PLOTS_CSS)
 *   ../vscode-extension/webview/plots.js  -> src/generated/assets.ts (PLOTS_JS)
 *
 * Same single-source rule the VS Code extension's sync-assets.mjs and the
 * PyPI wheel's force-include follow: the ML layer lives once, in ../frontend,
 * and every shell copies it in rather than forking it.
 *
 * Why the Python travels *inside the JavaScript bundle* rather than being
 * pip-installed: the environment the Jupyter server runs in is routinely not
 * the environment the kernel runs in, so a server-side install would land in
 * the wrong Python — and in JupyterLite there is no server to install into at
 * all. The kernel gets the source pushed to it over the wire instead.
 *
 * Codegen rather than an import: @jupyter/builder's base rspack rules give
 * asset/source to .txt/.md/.raw.css and nothing else. .py and .csv have no
 * loader, and adding ones would put knowledge of Python in a second place.
 */

import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const repo = join(root, '..');

const TARGET = join(root, 'src', 'generated', 'assets.ts');

/** Sources, in the order they appear in the generated file. */
const SOURCES = [
  {
    name: 'LEARNER_SOURCE',
    path: join(repo, 'frontend', 'py', 'learner.py'),
    doc: 'The ML layer, shared verbatim with the web app and the VS Code extension.'
  },
  {
    name: 'RUNNER_SOURCE',
    path: join(root, 'python', 'learner_runner.py'),
    doc: 'The kernel-side half: execs LEARNER_SOURCE and serves its functions.'
  },
  {
    name: 'AIRFOIL_CSV',
    path: join(repo, 'frontend', 'data', 'airfoil.csv'),
    doc: 'Bundled sample. learner.py reads it from a path, so it is written into the kernel filesystem at boot.'
  },
  {
    name: 'PLOTS_CSS',
    path: join(repo, 'vscode-extension', 'webview', 'plots.css'),
    doc: 'The plots stylesheet, verbatim from the VS Code extension.'
  },
  {
    name: 'PLOTS_JS',
    path: join(repo, 'vscode-extension', 'webview', 'plots.js'),
    doc: 'The plots renderer, verbatim from the VS Code extension. Runs in an iframe so acquireVsCodeApi and the --vscode-* variables can be shimmed instead of forked.'
  }
];

/* Backslashes and backticks first, then `${` escaped at the `$` so a Python
 * f-string like f"{x}" or a CSS var() is never read as interpolation. */
function asTemplateLiteral(text) {
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const parts = [
  `/* GENERATED by scripts/gen-assets.mjs. Do not edit — the next build`,
  ` * overwrites it. Edit the sources listed in that script instead. */`,
  ''
];

for (const source of SOURCES) {
  let text;
  try {
    text = await readFile(source.path, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') {
      console.error(
        `gen-assets: ${relative(process.cwd(), source.path)} is missing.\n` +
          `It is the source of ${source.name} and must exist before the build.`
      );
      process.exit(1);
    }
    throw err;
  }
  parts.push(`/** ${source.doc} */`);
  parts.push(`export const ${source.name}: string = \`${asTemplateLiteral(text)}\`;`);
  parts.push('');
  console.log(`gen-assets: ${source.name} <- ${relative(repo, source.path)} (${text.length} bytes)`);
}

const out = parts.join('\n');

await mkdir(dirname(TARGET), { recursive: true });

/* Rewriting an identical file restarts tsc --watch and the labextension
 * watcher on every no-op build. */
let previous = null;
try {
  previous = await readFile(TARGET, 'utf8');
} catch {
  /* first run */
}
if (previous === out) {
  console.log('gen-assets: src/generated/assets.ts is up to date');
} else {
  await writeFile(TARGET, out, 'utf8');
  console.log('gen-assets: wrote src/generated/assets.ts');
}

/* The Lite demo site needs something in its file browser to open. */
await mkdir(join(root, 'lite', 'files'), { recursive: true });
await copyFile(
  join(repo, 'frontend', 'data', 'airfoil.csv'),
  join(root, 'lite', 'files', 'airfoil.csv')
);
console.log('gen-assets: lite/files/airfoil.csv');
